### ISSUE TITLE
在运行之后报错

### ISSUE THREAD

**Issue by sunnnnnner** [TriDiamond/hexo-theme-obsidian#140]
在 hexo server 运行之后 在 浏览器访问 ，然后就会报如下错误

INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR {
  err: TypeError: /tgz/nodejs/hexo/themes/obsidian/layout/layout.ejs:33
      31|         </span>
      32|         <small><%- link_to("https://github.com/TriDiamond/hexo-theme-obsidian/blob/master/CHANGELOG.md", 'v'+theme.version, {external: true})%></small>
   >> 33|         <% if (theme.beian.enable == true) { %>
      34|         </br>
      35|         <%= theme.beian.beianloc %>
      36|         <span class="gradient-text">
  
  Cannot read property 'enable' of undefined
      at eval (/tgz/nodejs/hexo/themes/obsidian/layout/layout.ejs:37:24)
      at layout (/tgz/nodejs/hexo/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiled (/tgz/nodejs/hexo/node_modules/hexo/lib/theme/view.js:136:50)
      at _View.render (/tgz/nodejs/hexo/node_modules/hexo/lib/theme/view.js:39:17)
      at /tgz/nodejs/hexo/node_modules/hexo/lib/theme/view.js:51:25
      at tryCatcher (/tgz/nodejs/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/tgz/nodejs/hexo/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/tgz/nodejs/hexo/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/tgz/nodejs/hexo/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/tgz/nodejs/hexo/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/tgz/nodejs/hexo/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/tgz/nodejs/hexo/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/tgz/nodejs/hexo/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/tgz/nodejs/hexo/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (node:internal/timers:463:21) {
    path: '/tgz/nodejs/hexo/themes/obsidian/layout/layout.ejs'
  }
} Render HTML failed: index.html
Unhandled rejection TypeError: /tgz/nodejs/hexo/themes/obsidian/layout/layout.ejs:33
    31|         </span>
    32|         <small><%- link_to("https://github.com/TriDiamond/hexo-theme-obsidian/blob/master/CHANGELOG.md", 'v'+theme.version, {external: true})%></small>
 >> 33|         <% if (theme.beian.enable == true) { %>
    34|         </br>
    35|         <%= theme.beian.beianloc %>
    36|         <span class="gradient-text">

Cannot read property 'enable' of undefined
    at eval (/tgz/nodejs/hexo/themes/obsidian/layout/layout.ejs:37:24)
    at layout (/tgz/nodejs/hexo/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/tgz/nodejs/hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/tgz/nodejs/hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /tgz/nodejs/hexo/node_modules/hexo/lib/theme/view.js:51:25
    at tryCatcher (/tgz/nodejs/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/tgz/nodejs/hexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/tgz/nodejs/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/tgz/nodejs/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/tgz/nodejs/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/tgz/nodejs/hexo/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/tgz/nodejs/hexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/tgz/nodejs/hexo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/tgz/nodejs/hexo/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:463:21)

^CINFO  Have a nice day

**Comment by kcn3388** [comment]
pull最新版本试试
![image](https://user-images.githubusercontent.com/25716090/121320412-b7e08780-c93f-11eb-96ee-bc4b7e36218a.png)

**Comment by kcn3388** [comment]
已定位原因，config模板文件写错了，详细配置以上图为准，详细commit：https://github.com/kcn3388/hexo-theme-obsidian/commit/c7818fef7304092eee21dfeb4d135cf4013e1277
Already fix, config file error, view details here: https://github.com/kcn3388/hexo-theme-obsidian/commit/c7818fef7304092eee21dfeb4d135cf4013e1277

**Comment by sunnnnnner** [comment]
> 已定位原因，config模板文件写错了，详细配置以上图为准，详细commit：[kcn3388@c7818fe](https://github.com/kcn3388/hexo-theme-obsidian/commit/c7818fef7304092eee21dfeb4d135cf4013e1277)
> Already fix, config file error, view details here: [kcn3388@c7818fe](https://github.com/kcn3388/hexo-theme-obsidian/commit/c7818fef7304092eee21dfeb4d135cf4013e1277)

你所说的confi 模板文件是那个目录的文件

**Comment by sunnnnnner** [comment]
我查看 master分支，已经是最新的commit了

**Comment by sunnnnnner** [comment]
在把_config_template_cn.yml 文件完全复制过去可以了

**Comment by kcn3388** [comment]
> 在把_config_template_cn.yml 文件完全复制过去可以了

以我回复的图为准
提交的commit在我的fork里面，作者最近忙没时间pass pull request

**Comment by TriDiamond** [comment]
> > 在把_config_template_cn.yml 文件完全复制过去可以了
> 
> 以我回复的图为准
> 提交的commit在我的fork里面，作者最近忙没时间pass pull request

PR 已经合并了～

**Comment by BaHui** [comment]
您好, 我使用了最新的master代码, 依然是报错

**Comment by kcn3388** [comment]
> 您好, 我使用了最新的master代码, 依然是报错

请post报错
可能的解决方法：在template进行自定义，然后修改template的名字为_config.yml

**Comment by BaHui** [comment]
Unhandled rejection TypeError: /Users/qiaobahui/Coding/blog/themes/obsidian/layout/layout.ejs:51
    49| </footer>
    50| <%- partial('_partial/mathjax', null, {cache: true}) %>
 >> 51| <%- partial('_partial/scripts', null, {cache: true}) %>
    52| <% if (theme.aplayer.enable == true) { %>
    53| 
    54| <script>document.write(aplayerconf)</script>

/Users/qiaobahui/Coding/blog/themes/obsidian/layout/_partial/scripts.ejs:1
 >> 1| <% if (theme.gitalk.enable == true) { %> <%-
    2| css(['//cdn.bootcss.com/gitalk/1.5.0/gitalk.min.css'])%> <%-
    3| js(['//cdn.bootcss.com/gitalk/1.5.0/gitalk.min.js'])%> <% } %> <%-
    4| js(['//cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js', 'js/plugin.js', 'js/obsidian.js',

Cannot read property 'enable' of undefined
    at eval (/Users/qiaobahui/Coding/blog/themes/obsidian/layout/_partial/scripts.ejs:10:25)
    at scripts (/Users/qiaobahui/Coding/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/Users/qiaobahui/Coding/blog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/Users/qiaobahui/Coding/blog/node_modules/hexo/lib/theme/view.js:59:25)
    at /Users/qiaobahui/Coding/blog/node_modules/hexo/lib/plugins/helper/partial.js:31:52
    at Cache.apply (/Users/qiaobahui/Coding/blog/node_modules/hexo-util/lib/cache.js:27:46)
    at Object.fragmentCache (/Users/qiaobahui/Coding/blog/node_modules/hexo/lib/plugins/helper/fragment_cache.js:11:34)
    at Object.partial (/Users/qiaobahui/Coding/blog/node_modules/hexo/lib/plugins/helper/partial.js:31:17)
    at eval (/Users/qiaobahui/Coding/blog/themes/obsidian/layout/layout.ejs:69:17)
    at layout (/Users/qiaobahui/Coding/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/qiaobahui/Coding/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/qiaobahui/Coding/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/qiaobahui/Coding/blog/node_modules/hexo/lib/theme/view.js:51:25
    at tryCatcher (/Users/qiaobahui/Coding/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/qiaobahui/Coding/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/qiaobahui/Coding/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/qiaobahui/Coding/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/qiaobahui/Coding/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/qiaobahui/Coding/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/qiaobahui/Coding/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/qiaobahui/Coding/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/qiaobahui/Coding/blog/node_modules/bluebird/js/release/async.js:15:14)

**Comment by BaHui** [comment]
您好, 我使用的是master上面的config代码, 重命名为_config.yml. clean之后重新部署还是报了这个错, 请问是什么原因?

**Comment by kcn3388** [comment]
> 您好, 我使用的是master上面的config代码, 重命名为_config.yml. clean之后重新部署还是报了这个错, 请问是什么原因?

请post一下_config.yml的详细内容

**Comment by BaHui** [comment]
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 123
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://bahui.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: true
  tab_replace:
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
  
codemirror:
  modes: ['javascript', 'css', 'xml', 'htmlmixed', 'clike', 'php', 'shell', 'python']

search:
  path: search.xml
  field: post
  content: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: obsidian

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:BaHui/BaHui.github.io.git
  branch: master

**Comment by kcn3388** [comment]
> 您好, 我使用的是master上面的config代码, 重命名为_config.yml. clean之后重新部署还是报了这个错, 请问是什么原因?

已定位原因，稍后会有pr

**Comment by kcn3388** [comment]
> 您好, 我使用的是master上面的config代码, 重命名为_config.yml. clean之后重新部署还是报了这个错, 请问是什么原因?

Pull request already pushed.
