### ISSUE TITLE
hexo g 出现一些错误不知怎么解决

### ISSUE THREAD

**Issue by smile0304** [TriDiamond/hexo-theme-obsidian#2]
不知道是代码的问题还是我部署的问题
nodejs 版本:v12.12
平台: window10 ubuntu16.04都测试了

```shell

D:\blog_test

ERROR D:\blog_test\themes\obsidian\layout\post.ejs:4
    2|     <%- partial("_partial/post/header")%>
    3|     <div class="section">
 >> 4|         <%- partial("_partial/post/article")%>
    5|     </div>
    6| </div>

D:\blog_test\themes\obsidian\layout\_partial\post\article.ejs:12
    10|         <div class="else">
    11|             <p class="animated fadeInDown">
 >> 12|                 <a href="<%- '/categories/' + page.categories.data[0].name %>"><b>「 </b><%- page.categories.data[0].name.toUpperCase() %><b>
」</b> </a>
    13|                 <%- page.date.locale(config.language || '').format("MMMM DD, YYYY") %>
    14|             </p>
    15|             <h3 class="post-title animated fadeInDown"><%- link_to(page.path, page.title || "Untitled", {class: ""}) %></h3>

Cannot read property 'name' of undefined
TypeError: D:\blog_test\themes\obsidian\layout\post.ejs:4
    2|     <%- partial("_partial/post/header")%>
    3|     <div class="section">
 >> 4|         <%- partial("_partial/post/article")%>
    5|     </div>
    6| </div>

D:\blog_test\themes\obsidian\layout\_partial\post\article.ejs:12
    10|         <div class="else">
    11|             <p class="animated fadeInDown">
 >> 12|                 <a href="<%- '/categories/' + page.categories.data[0].name %>"><b>「 </b><%- page.categories.data[0].name.toUpperCase() %><b>
」</b> </a>
    13|                 <%- page.date.locale(config.language || '').format("MMMM DD, YYYY") %>
    14|             </p>
    15|             <h3 class="post-title animated fadeInDown"><%- link_to(page.path, page.title || "Untitled", {class: ""}) %></h3>

Cannot read property 'name' of undefined
    at eval (eval at compile (D:\blog_test\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:14:58)
    at returnedFn (D:\blog_test\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\blog_test\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (D:\blog_test\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (D:\blog_test\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at compile (D:\blog_test\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:14:17)
    at returnedFn (D:\blog_test\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\blog_test\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\blog_test\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog_test\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (D:\blog_test\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog_test\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog_test\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:452:10)
    at resume_ (_stream_readable.js:899:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR D:\blog_test\themes\obsidian\layout\index.ejs:3
    1| <%- partial("_partial/menu", null, {cache: true}) %>
    2| <div id="container">
 >> 3|     <%- partial("_partial/screen", null, {cache: false}) %>
    4|     <div id="primary">
    5|         <%- partial('_partial/list', {start: 1}) %>
    6|     </div>

D:\blog_test\themes\obsidian\layout\_partial\screen.ejs:28
    26|     <div id="post0" class="else">
    27|         <p class="animated fadeInDown">
 >> 28|             <a href="<%- '/categories/' + first.categories.data[0].name %>"><b>「 </b><%- first.categories.data[0].name.toUpperCase() %><b> 」
</b></a>
    29|             <%- first.date.locale(config.language || '').format("MMMM DD, YYYY") %>
    30|         </p>
    31|         <h3 class="post-title animated fadeInDown"><%- link_to(first.path, first.title || config.title, {class: "posttitle"}) %></h3>

Cannot read property 'name' of undefined
TypeError: D:\blog_test\themes\obsidian\layout\index.ejs:3
    1| <%- partial("_partial/menu", null, {cache: true}) %>
    2| <div id="container">
 >> 3|     <%- partial("_partial/screen", null, {cache: false}) %>
    4|     <div id="primary">
    5|         <%- partial('_partial/list', {start: 1}) %>
    6|     </div>

D:\blog_test\themes\obsidian\layout\_partial\screen.ejs:28
    26|     <div id="post0" class="else">
    27|         <p class="animated fadeInDown">
 >> 28|             <a href="<%- '/categories/' + first.categories.data[0].name %>"><b>「 </b><%- first.categories.data[0].name.toUpperCase() %><b> 」
</b></a>
    29|             <%- first.date.locale(config.language || '').format("MMMM DD, YYYY") %>
    30|         </p>
    31|         <h3 class="post-title animated fadeInDown"><%- link_to(first.path, first.title || config.title, {class: "posttitle"}) %></h3>

Cannot read property 'name' of undefined
    at eval (eval at compile (D:\blog_test\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:27:59)
    at returnedFn (D:\blog_test\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\blog_test\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (D:\blog_test\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (D:\blog_test\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at compile (D:\blog_test\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:12:17)
    at returnedFn (D:\blog_test\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\blog_test\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\blog_test\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog_test\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (D:\blog_test\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog_test\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog_test\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:452:10)
    at resume_ (_stream_readable.js:899:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

INFO  Start processing
INFO  Files loaded in 234 ms
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: font/Rubik-Bold-kern-latin.woff2
INFO  Generated: img/favicon.png
INFO  Generated: img/cover.jpg
INFO  Generated: font/Rubik-Regular-kern-latin.woff2
INFO  Generated: img/logo.png
INFO  Generated: archives/2019/10/index.html
INFO  Generated: archives/2019/index.html
INFO  Generated: css/theme.css
INFO  Generated: css/dracula.css
INFO  Generated: js/jquery.truncate.min.js
INFO  Generated: js/jquery.truncate.js
INFO  Generated: js/obsidian.js
INFO  Generated: js/plugin.js
INFO  Generated: img/welcome-cover.jpg
INFO  Generated: js/obsidian.min.js
INFO  Generated: 2019/10/18/hello-world/index.html
INFO  Generated: css/obsidian.css
INFO  Generated: js/jquery.min.js
INFO  Generated: img/profile.jpg
INFO  Generated: statics/chengdu.mp3
INFO  22 files generated in 713 ms
```

**Comment by TriDiamond** [comment]
你有文章没有分类对不对？这个可以说是分类回去那里的判断问题。没有考虑到没有设置分类的情况。这个我修复一下判断就好了。

**Comment by smile0304** [comment]
是的，我的文章并没有分类。hexo初始化后我直接安装了该主题，然后启动了服务。


主题很棒,非常喜欢

**Comment by TriDiamond** [comment]
> 是的，我的文章并没有分类。hexo初始化后我直接安装了该主题，然后启动了服务。
> 
> 主题很棒,非常喜欢

已经在v1.3.1解决了这个问题. 更新主题文件就可以了. 谢谢你的支持!
