### ISSUE TITLE
打开网页后报错

### ISSUE THREAD

**Issue by dong628** [TriDiamond/hexo-theme-obsidian#45]
本地端口运行时控制台显示错误信息，网页没有内容

Unhandled rejection ReferenceError: /home/archer/Blogs/JingleiDong&#39;s Blog/themes/obsidian/layout/index.ejs:3
    1| <%- partial("_partial/menu", null, {cache: true}) %>                                                                   
    2| <div id="container">                                                                                                   
 >> 3|     <%- partial("_partial/screen", null, {cache: false}) %>                                                            
    4|     <div id="primary">
    5|         <%- partial('_partial/list', {start: 1}) %>
    6|     </div>

/home/archer/Blogs/JingleiDong&#39;s Blog/themes/obsidian/layout/_partial/screen.ejs:92
    90|         <div class="md-content animated fadeIn">
    91|             <% if (theme.html_truncate.enable) { %>
 >> 92|             <%- htmlTruncate(first.content, first.preview || theme.html_truncate.coverLength, {
    93|                     ellipsis: theme.html_truncate.ellipsis,
    94|                     excludes: theme.html_truncate.excludes,
    95|                     keepWhitespaces: theme.html_truncate.keepWhitespaces,

htmlTruncate is not defined
    at eval (eval at compile (/home/archer/Blogs/JingleiDong's Blog/node_modules/ejs/lib/ejs.js:652:12), <anonymous>:133:7)
    at screen (/home/archer/Blogs/JingleiDong's Blog/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiledSync (/home/archer/Blogs/JingleiDong's Blog/node_modules/hexo/lib/theme/view.js:132:22)
    at viewFn.View.renderSync (/home/archer/Blogs/JingleiDong's Blog/node_modules/hexo/lib/theme/view.js:60:23)
    at Object.partial (/home/archer/Blogs/JingleiDong's Blog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (eval at compile (/home/archer/Blogs/JingleiDong's Blog/node_modules/ejs/lib/ejs.js:652:12), <anonymous>:11:17)
    at index (/home/archer/Blogs/JingleiDong's Blog/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiled (/home/archer/Blogs/JingleiDong's Blog/node_modules/hexo/lib/theme/view.js:136:48)
    at viewFn.View.render (/home/archer/Blogs/JingleiDong's Blog/node_modules/hexo/lib/theme/view.js:41:15)
    at /home/archer/Blogs/JingleiDong's Blog/node_modules/hexo/lib/hexo/index.js:61:21
    at tryCatcher (/home/archer/Blogs/JingleiDong's Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/archer/Blogs/JingleiDong's Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/archer/Blogs/JingleiDong's Blog/node_modules/hexo/lib/hexo/router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:524:10)
    at resume_ (_stream_readable.js:1007:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by gordonfang199649** [comment]
我也是在本機執行的時候報錯，htmlTruncate尚未定義。

**Comment by gordonfang199649** [comment]
我在本地端運行服務器時，發現原來是有些腳本檔缺少了import的library，你使用npm將缺漏的library下載補上，就可以正常運行了。

**Comment by TriDiamond** [comment]
@gordonfang199649 @dong628 这个我后面会补上那个js的依赖library。就不需要用npm补充了。

**Comment by dong628** [comment]
> @gordonfang199649 @dong628 这个我后面会补上那个js的依赖library。就不需要用npm补充了。

貌似是少了个 lodash 的依赖库。我不懂js，请问依赖库都在哪里存放？

**Comment by gordonfang199649** [comment]
@dong628 你可以等TriDiamond 大大補上library，我的做法是切themes\obsidian這層目錄，使用npm將以下用到的library下載下來，library會放在node_modules內，你可以從package.json看到目前dependencies library的版本，希望以上資訊對你有幫助。

下載指令: npm install library的名字 --save;

    "css-select": "^2.1.0",
    "lodash.assign": "^4.2.0",
    "lodash.assignin": "^4.2.0",
    "lodash.bind": "^4.2.1",
    "lodash.defaults": "^4.2.0",
    "lodash.filter": "^4.6.0",
    "lodash.flatten": "^4.4.0",
    "lodash.foreach": "^4.5.0",
    "lodash.get": "^4.4.2",
    "lodash.map": "^4.6.0",
    "lodash.merge": "^4.6.2",
    "lodash.pick": "^4.4.0",
    "lodash.reduce": "^4.6.0",
    "lodash.reject": "^4.6.0",
    "lodash.some": "^4.6.0"

**Comment by gordonfang199649** [comment]
@TriDiamond 感謝大大 👍

**Comment by dong628** [comment]
@TriDiamond @gordonfang199649  感谢各位大佬！！
