### ISSUE TITLE
启动报错，访问也出错

### ISSUE THREAD

**Issue by nic519** [TriDiamond/hexo-theme-obsidian#61]
好吧。连续装了lodash.*就可以了

**Comment by nic519** [comment]
上面是运行报的错。

下面是启动的时候报的错：

MacBook-Pro:blog-zhuhaiting Nicholas$ hexo s
ERROR Script load failed: themes/obsidian/scripts/helpers/hexo-html-truncate.js
Error: Cannot find module 'lodash.assignin'
Require stack:
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/cheerio.js
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/helpers/hexo-html-truncate.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/cheerio.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/helpers/hexo-html-truncate.js:7:15
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
ERROR Script load failed: themes/obsidian/scripts/libs/cheerio/api/attributes.js
Error: Cannot find module 'css-select'
Require stack:
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/static.js
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/attributes.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/static.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/attributes.js:1:74
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
ERROR Script load failed: themes/obsidian/scripts/libs/cheerio/api/css.js
Error: Cannot find module 'lodash.pick'
Require stack:
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/css.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/css.js:3:13
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
ERROR Script load failed: themes/obsidian/scripts/libs/cheerio/api/forms.js
Error: Cannot find module 'lodash.map'
Require stack:
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/forms.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/forms.js:7:12
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
ERROR Script load failed: themes/obsidian/scripts/libs/cheerio/api/manipulation.js
Error: Cannot find module 'css-select'
Require stack:
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/static.js
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/manipulation.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/static.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/manipulation.js:2:9
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
ERROR Script load failed: themes/obsidian/scripts/libs/cheerio/api/traversing.js
Error: Cannot find module 'css-select'
Require stack:
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/traversing.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/api/traversing.js:1:79
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
ERROR Script load failed: themes/obsidian/scripts/libs/cheerio/cheerio.js
Error: Cannot find module 'lodash.assignin'
Require stack:
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/cheerio.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/cheerio.js:8:15
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
ERROR Script load failed: themes/obsidian/scripts/libs/cheerio/static.js
Error: Cannot find module 'css-select'
Require stack:
- /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/static.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/themes/obsidian/scripts/libs/cheerio/static.js:6:14
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/hexo/lib/hexo/index.js:293:14
    at tryCatcher (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/promise.js:673:18)
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Nicholas/Documents/MAMP/host/blog-zhuhaiting/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
