### ISSUE TITLE
htmlTruncate is not defined

### ISSUE THREAD

**Issue by hongzhi725** [TriDiamond/hexo-theme-obsidian#68]
`htmlTruncate is not defined
    at eval (F:\Development\blog\themes\obsidian\layout\_partial\screen.ejs:138:7)
    at screen (F:\Development\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync.locals [as _compiledSync] (F:\Development\blog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (F:\Development\blog\node_modules\hexo\lib\theme\view.js:60:23)
    at Object.partial (F:\Development\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (F:\Development\blog\themes\obsidian\layout\index.ejs:13:17)
    at index (F:\Development\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled.locals [as _compiled] (F:\Development\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (F:\Development\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at F:\Development\blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (F:\Development\blog\node_modules\bluebird\js\release\util.js:16:23)
    at F:\Development\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\Development\blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:933:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
INFO  Good bye
`
当下载本主题，并且更改主题后重新hexo server，刷新页面，会弹出这种提示。

**Comment by Andy1246** [comment]
试一试 `cd themes\obsidian && npm i --save`
