### ISSUE TITLE
‘hexo clean‘Running Times Wrong 

### ISSUE THREAD

**Issue by zhenglixin1** [TriDiamond/hexo-theme-obsidian#95]
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\api\css.js
Error: Cannot find module 'lodash.pick'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\api\css.js:3:13
    at readFile.then.script (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:293:14)
    at tryCatcher (E:\basicData\staticBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at E:\basicData\staticBlog\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\basicData\staticBlog\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\api\forms.js
Error: Cannot find module 'lodash.map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\api\forms.js:7:12
    at readFile.then.script (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:293:14)
    at tryCatcher (E:\basicData\staticBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at E:\basicData\staticBlog\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\basicData\staticBlog\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\cheerio.js
Error: Cannot find module 'lodash.assignin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\cheerio.js:8:15
    at readFile.then.script (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:293:14)
    at tryCatcher (E:\basicData\staticBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at E:\basicData\staticBlog\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\basicData\staticBlog\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
ERROR Script load failed: themes\obsidian\scripts\helpers\hexo-html-truncate.js
Error: Cannot find module 'lodash.assignin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\cheerio.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\basicData\staticBlog\themes\obsidian\scripts\helpers\hexo-html-truncate.js:7:15
    at readFile.then.script (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:293:14)
    at tryCatcher (E:\basicData\staticBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:559:17)
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\static.js
Error: Cannot find module 'css-select'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\static.js:6:14
    at readFile.then.script (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:293:14)
    at tryCatcher (E:\basicData\staticBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at E:\basicData\staticBlog\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\basicData\staticBlog\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\api\attributes.js
Error: Cannot find module 'css-select'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\static.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\api\attributes.js:1:74
    at readFile.then.script (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:293:14)
    at tryCatcher (E:\basicData\staticBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:559:17)
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\api\traversing.js
Error: Cannot find module 'css-select'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\api\traversing.js:1:79
    at readFile.then.script (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:293:14)
    at tryCatcher (E:\basicData\staticBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at E:\basicData\staticBlog\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\basicData\staticBlog\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\api\manipulation.js
Error: Cannot find module 'css-select'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\static.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:280:23)
    at E:\basicData\staticBlog\themes\obsidian\scripts\libs\cheerio\api\manipulation.js:2:9
    at readFile.then.script (E:\basicData\staticBlog\node_modules\hexo\lib\hexo\index.js:293:14)
    at tryCatcher (E:\basicData\staticBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (E:\basicData\staticBlog\node_modules\bluebird\js\release\promise.js:559:17)

**Comment by Flexiston** [comment]
`cd themes\obsidian && npm install --save`

**Comment by TriDiamond** [comment]
已经在说明文档中补充了这个步骤了，谢谢大家的支持！
